### ISSUE TITLE
Telepresence needs a mechanism for better output

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#572]
Telepresence doesn't make it clear what's going on at any moment. Better output during startup and shutdown, as well as explicit indications of when those phases start and end, would significantly improve the user experience. Sometimes it's not clear that output is from Telepresence (or its subordinate tools) rather than the user's process. And sometimes it's not clear whether Telepresence's output represents a status update, a fatal error message, or something else. There are many issues that touch on bits and pieces of this. 

Let's implement some basic tools for notices, error messages, etc., so that we can address those issues going forward in a consistent way.

Goals
- [x] Make it clear what output is from Telepresence (#701)
- [x] Make it clear what's startup, when stuff is running, and when shutdown is happening
- [x] Make error messages clearly as errors (e.g., "'ip addr' nor 'ifconfig' available" is unclear)
- [x] One spot for isatty() stuff, deciding whether we're interactive, controlling verbosity (#720)
- [x] No more print() in the code other than this tooling (#701)
- [ ] Make it easy to refer to documentation and issues

Non-goals (file other issues for these)
- New or better error handling
- Different control flow/UX

**Comment by ark3** [comment]
See also the Output column of the [Blobs project](https://github.com/datawire/telepresence/projects/7).

**Comment by ark3** [comment]
There has been some work to this end in #701, #720, and #732. We should reevaluate the status of this issue.
